[package]
name = "redact-core"
description = "Domain model, traits and errors for redact-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lopdf.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
